name: Dont Panic
markdown: redcarpet
pygments: true
github: www.github.com/chrismatheson
about:
urls:
    - text: github
      url: https://github.com/chrismatheson
    - text: twitter
      url: https://twitter.com/chrismatheson
    - text: email
      url: mailto://chris@matheson.it